---
groups: !!pairs
- venia:
    label: "Venia"
    items:
    - "principles"
- foundation:
    label: "Foundation"
    items:
    - "design-tokens"
    - "color"
    - "typography"
- components:
    label: "Components"
    items:
    - "app-bar"
    - "button"
    - "button-group"
    - group:
        label: "Inputs"
        items:
        - "select-input"
        - "text-input"

pages: !!pairs
- app-bar: "App bar"
- button: "Button"
- button-group: "Button group"
- color: "Color"
- design-tokens: "Design tokens"
- principles: "Principles"
- select-input: "Select input"
- text-input: "Text input"
- typography: "Typography"
